{
  "openapi": "3.0.2",
  "info": {
    "title": "PACS.AI Inference Model API",
    "description": "API Documentation of PACS.AI Model Inference",
    "termsOfService": "https://github.com/HeartWise-AI",
    "contact": {
      "name": "HeartWise AI",
      "email": "hello@heartwise.ai"
    },
    "version": "1.0.0"
  },
  "servers": [
    {
      "url": "http://cathef/api",
      "description": "Docker"
    },
    {
      "url": "http://localhost:8000",
      "description": "Local"
    }
  ],
  "tags": [
    {
      "name": "inference",
      "description": "Inference service"
    }
  ],
  "paths": {
    "/inference/predict": {
      "post": {
        "tags": ["inference"],
        "summary": "Predict",
        "description": "Creates a prediction request",
        "requestBody": {
          "description": "Prediction request",
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/PredictRequest"
              }
            }
          },
          "required": true
        },
        "responses": {
          "201": {
            "description": "Success",
            "content": {
              "application/json": {
                "schema": {
                  "allOf": [
                    {
                      "$ref": "#/components/schemas/APIResponse"
                    },
                    {
                      "type": "object",
                      "properties": {
                        "data": {
                          "$ref": "#/components/schemas/PredictResponse"
                        }
                      }
                    }
                  ]
                },
                "examples": {
                  "JSON": {
                    "summary": "Successful JSON prediction request",
                    "value": {
                      "success": true,
                      "message": "Registration request created successfully",
                      "data": {
                        "diagnosis": "limit",
                        "predictions": {
                          "Vessel": {
                            "probability": 56.534433434343,
                            "confidence": "intermediate",
                            "presentable": true,
                            "displayResult": "Left Coronary"
                          }
                        },
                        "modelRecommendations": {
                          "en": "Recommendation for the next model",
                          "fr": "Recommandation pour le prochain modèle",
                          "presentable": true
                        }
                      }
                    }
                  },
                  "OHIF_ANNOTATIONS": {
                    "summary": "Successful OHIF Annotations prediction request",
                    "value": {
                      "success": true,
                      "message": "Registration request created successfully",
                      "data": {
                        "metadata": {
                          "key": "value pair"
                        },
                        "segmentations": [],
                        "boundingBoxes": [],
                        "measurements": []
                      }
                    }
                  },
                  "HTML": {
                    "summary": "Successful HTML prediction request",
                    "value": {
                      "success": true,
                      "message": "Registration request created successfully",
                      "data": {
                        "htmlBase64": "PCFET0NUWVBFIGh0bWw+DQo8aHRtbCBsYW5nPSJlbiI+DQogIDxoZWFkPg0KICAgIDxtZXRhIGNoYXJzZXQ9IlVURi04IiAvPg0KICAgIDxtZXRhIG5hbWU9InZpZXdwb3J0IiBjb250ZW50PSJ3aWR0aD1kZXZpY2Utd2lkdGgsIGluaXRpYWwtc2NhbGU9MS4wIiAvPg0KICAgIDx0aXRsZT5TdWNjZXNzPC90aXRsZT4NCiAgICA8c3R5bGU+DQogICAgICBib2R5IHsNCiAgICAgICAgbWFyZ2luOiAwOw0KICAgICAgICBoZWlnaHQ6IDEwMHZoOw0KICAgICAgICBkaXNwbGF5OiBmbGV4Ow0KICAgICAgICBhbGlnbi1pdGVtczogY2VudGVyOw0KICAgICAgICBqdXN0aWZ5LWNvbnRlbnQ6IGNlbnRlcjsNCiAgICAgICAgZm9udC1mYW1pbHk6IHN5c3RlbS11aSwgLWFwcGxlLXN5c3RlbSwgc2Fucy1zZXJpZjsNCiAgICAgICAgYmFja2dyb3VuZC1jb2xvcjogI2Y5ZmFmYjsNCiAgICAgIH0NCiAgICAgIC5tZXNzYWdlIHsNCiAgICAgICAgY29sb3I6ICMxNTgwM2Q7DQogICAgICAgIGZvbnQtc2l6ZTogMS4yNXJlbTsNCiAgICAgICAgcGFkZGluZzogMnJlbTsNCiAgICAgICAgYmFja2dyb3VuZC1jb2xvcjogd2hpdGU7DQogICAgICAgIGJvcmRlci1yYWRpdXM6IDAuNXJlbTsNCiAgICAgICAgYm94LXNoYWRvdzogMCAxcHggM3B4IHJnYmEoMCwgMCwgMCwgMC4xKTsNCiAgICAgIH0NCiAgICA8L3N0eWxlPg0KICA8L2hlYWQ+DQogIDxib2R5Pg0KICAgIDxkaXYgY2xhc3M9Im1lc3NhZ2UiPlJlZ2lzdHJhdGlvbiByZXF1ZXN0IGNyZWF0ZWQgc3VjY2Vzc2Z1bGx5PC9kaXY+DQogIDwvYm9keT4NCjwvaHRtbD4="
                      }
                    }
                  },
                  "WEB_APP": {
                    "summary": "Successful WEB_APP prediction request",
                    "value": {
                      "success": true,
                      "message": "Registration request created successfully",
                      "data": {
                        "webappPath": "/app/viewer",
                        "webappDataBase64": "base64 encoded webapp data..."
                      }
                    }
                  },
                  "PDF": {
                    "summary": "Successful PDF prediction request",
                    "value": {
                      "success": true,
                      "message": "Registration request created successfully",
                      "data": {
                        "pdfBase64": "JVBERi0xLjMKJcTl8uXrp/Og0MTGCjMgMCBvYmoKPDwgL0ZpbHRlciAvRmxhdGVEZWNvZGUgL0xlbmd0aCAzMTYwID4+CnN0cmVhbQp4AcVc2ZIcRxV9z69IIcuult2lytqLAQMWkoVZZQb8gHlSwAMRIsLo/yM4udxTudT0TE/3dAcB0+qqvHlv5jl3y2x+0u/1T9rMeo//jqbV09Lq//1L/6D/q1+9/mT0h0+6cf/59AEvNnXb+3/bDxgyzF2NER8+qm9u8bRpGqNvP+jBj8Gf2TR1N8+tHtpG337Ur25vW413/q2rZz/b6dv/6De30KHUQj1GCw0tormHsW4W09m5VTr380NTH78A6sPHbOqpq00zLaXZ/9DVZzvd1Z2uXuzsgurq852e60lXX+z0Hl+o6sfKPjG6+nHnvsKnl+HhOupLefSV+zDEb+9r/1Dlstfh2aTx6Fc7vVj9MIMxVo1SsSBfV02wgUrwiXEqwLx2p/+pb79bN9oCSz0UWOm6mmFeaovTCE7Kw8mulcDpEFJTgW076H5YAjT7IOvZKqpE5hngYWftlllm9YQAMsAIM1tIAJ9u5QEVQAJbAI3sB1W9wMY51GBT3F8PFowJr/idxMbNQI0b5bfSicE29fWoq/1OucHYLbfVIowygIH9aDXBBmNiiKAsv7H4BsoNFrftTpnBKgmt3Syd/QtAUlpvp8GbuTm6svM0da+rwc+j1kHjPlgo4kQ8FYDWJbLostQ9LisFgmlGU1vvV+wLNFICrKdDQzelaKimB2BQHeWjU4Pbvq0bM466c1MreGa4dO+ZHzD1EeGh8I7t0NZmapcwtQ0KYWpwYJZtXmT/fy4YqXeqdXAlFm9+IfAUWsBpxYSBPPvF4vA7W1CCAp3F4sud8sD+pX0BCCRaLSbNYr/CzKMdC5U6987X+bv+DUXoky45aMG0Ca5LV4UIsde7ULh/2kRhuXH4d2ttCEMcsUomPNbHms4q6mER9ka5gP3UsIBXbKfxWjzwU1+FB4XV4MGvBPXRZgfgOo+sKvpBIvfXAfyCFzKHSBJHn4FeVb+xkQFQp1Bhn/wVQHOyG0DadCFagVgQbca6U/YDcP5NoEr81h0kIuCFCoHfqsJgkNSzFh/iKIdHdAZCbBfb7iIrbBwRZUqeMGLo4yKGGRDUzGQxG9LLizlQyxQzXI0pburrMCW3Gkx5bf01gneUo/SC2jhkJChZX8DgwTrmMjl5ASh5YDs8I2VCTABBHMwkjtzBKF39VghMeMucRkJPLB/yBL4ugJE366iQiZGBgasu+rh08Y3Ns6Ar5DoZJLMoyaFvv52xbI5aWUBSdj3dA77xLntFVz0li3byN3MTysbQfW8TSA4RzyChGkPHUGZ43Tcpqh5Uh6Y5jhk7VFZ9RpaLBTMz9NeiqJ/6KhQtrPYUdZCSwPQ7xIrWsskyQCJGnM3A2aOgIGQE0MSvrfY2axxlk6JQ4wDGiBggUlLjZKFPV4ia+86WS8w4Q03lymcng/GTEZWa+Ggn3gCRS9yMj1ce7M5EBEtMUnCJySytjYjhZs8cyFbkz4dQ4TQYLzdcZL8VCqWgXyaOKBS0SbZbUSn4xJvIbmJyEJcJNe3gGtFEUTPTQlfwXH7LIROprdtFv4CYdNMfPKwvBX+g1o6QmW1Do5l1gVGb/d9b5J1UbiFkL524g9BneEiNd1KhJTXeOvMDSzx1dAcw9bws8ZYuzY3gDEZhs8SKHEchzpU4+vbz0Lcg6XKm57G8IHvsOEIBuMj8nLBMBUhBeTfXgP2UVYOpvaveQ8KBgPidJAi5TKsXHJd8TWaWzkf4VJB4XVqVVooitBgBg+5wUMu6X7ASCZHIEN5nLk8eb01BKivbSjmhfWHGFp2ytgOpUoDFTD6uD9i1d0t6ssbPHm0Q35teWyDMHGUFF0amgIWoTZZ30KJGxu8RjJo4HxS4EM2NZKKyZ38IuZ/kaDY+u9LOIZIO/Y/2NQQzzwKPD1UBdNxf19I/YX/nYa4XY4zGAl1kW9zpRZueXtg+7X6Rg4t1g/70Z5DFLXRirzrDQUrmRidkxv3ktEhXwfrRIqxyX2U76TqEwmEHXZK/h4+R7ymKFTeHFrJyN6TWLq71oC6XxzuucyYIplhISx0SdV6+2KlkOU9xD0tjcE6Asx9sX7pwsX84I6u3Dr8cfMyApqo7+GJ34NnBZOMMJ1/tMNT9ONtjvcFk5j95zoGw18+ofOzcueWHkqxz2D0j5PZm3LAbfGGeL87t5qaAJxNTujr04Xo0ZYUo4kLxYpF7uODIgXfSc6OsgPQtN/sWKg+2K8dm4Pgu8bHqpBi64MhjMT18bAmTgxB99BHYnSxpcaZ3PZZg9quxZMPyi7GksBsswan0fkgODxkJJKkU1izEusuqW9v8lWdsXxHaKBFLdjHVsZEjbW/bhBT95DX7kED0l4fnnTaeKN4wOCEdWcxUzzbd3BdrdumA0k4sI6WYu2BAwezXo0pp+eWoktsNqrwGZpFDCeSZFwlQWSOm9dyXtohdz/RBOXCkt99QQsmebSrIOT4oerbUaVymehzGFrblNl8a6l2XN1CfXRDqmP1qUN+w/EmgvhmQmUUVKwDQv3+O9AlYBURRulYvzbP3z7/6Hl81YEJtO6cGfV1AvwTkIw+kR3SxpgWXqfbRqpQ3dY4r9vfdwpPmUta5C4OturIfsisfWNy/Xr6whBopyqEG72DAMTlXdcNIH3yePMjrRrVeGBIvyPSB3o3C7rvi49rmJY4eeWA74T5gO/WoTAqbL+3YBnQKrpfuYvZ0yx902eiIcry88cOicMPyJ3Fsa9O/pTsr7AbUmYBKFAdcXWEnZ6nyPZvDcH+tzY+/cr2zqE8rbxLwJAfHEvnvkTo4Znkiqfi6BK814I343PSuwVFe/T2u4jmxogv7Ls4x47Lumk5T3FuuAbUKH1T1jm/xyK4QzVduw/Ez5PW2T/w3ZyQ+4Aadt5YrcmCNPrM1Lw7zEUKSNngIKWdJ500/4gquDSkFJi7uCqDFFV3BlHdXL9cfGkrLL+cKcrvhCmwa7siD+hKglS4RKRQn5e49gpiugFQgk0RmJO0efquqGMy62eVZtlIoSLjF70C6ty8okB+O4jXMcy5RbFnivtk91mh7KuAaY+A+jsbdya4U+qeF9vhgt5unehkR2o8EVehkHX+yu5k42+OCsS8azodrlkc306IQx34vZs+8yUE+n6PnytC+YfkhPp/Dbob2wm7weRTOmRDSSSMcI6fQO/Xgpkh4ugWXjnv8SMbi4cI70jfgAn7TUEIRi4K1YJ+tsWEW4Ta5M0Z3R1/2d9x+nup+7YHTEUozXBzDeruEr4ijoq/0YT06wHw7vg4eAhP5NOEo7yTtFJlpubE2utQJemVH7TTqxmICWZz3Skyh1utDYhPXgxZQBo2Ud2U9vCr+7pu7NMixxfGXVEmiPd5MoWmblo8snM2IU7BpwDFQBMKy2D2ycJ7sb7z8gVYp69yFM/o/8c/J3InahN5UkjHZNB7rh7DYYAewqQbMx79woIj/xQr7gGmfb63uw8rJguI9HN8ydThsKhQ6nEM+2um6mLO1InObN2Vf4abzvfeZTqroRriEuUHAw+TpdhyuJh9tfRTu5r7ulwnnVoXhgAJ+bCTM9l4AHie6EyvpCFnMA+jnoS/LIoXUZ+DgIJEi9E3n4FW49GuOTq7Ou1QylyeehJmlTBT5CW8dhRbeKJnFHS+qaB3okmCcy8e8Y46uj3AdOIW8Itew2NGhMFFzPaPxWvKFcim5WLIGqLzd7yM5PwfLqoi/5c0kvsH1os6iEV/hk2R9Nu5PR70sai3SpDsgmkBo6rbTjOIcoLfJ5TxnLWngHYvibl+GmEcYyHKKyoIcRkc5PLC76LsGyAXg1CANbcj0N1E/SGgmW0RsELdmB1xf2S0O4YZijLslS1VkGcMmucgpv7xyyPWtAIrG+1lgF3U847hfX1tOox/NkXxCrWTu+JWk3FntCBcGCaWNJfWKJksKBiD0ULwnUfQzLxu60DxHbed+cSkk44AVpzIfbyyKLLGempGZlEJcwF6/pNjnMkNW276gmIBy5cmSqGkNeiNdH3llU7tDtIlLhEfmQP4KF34CEGcMCrSRbSco6e2JStAh2zvhlAzOK2OBClEmpsvOcQm4fpyfd/FkEr5CzUSaQCTcU4/AFaT5++Zyeu69vt/09Bxxy4Fam9HVDLOvJ/poAHpfTr2O8DwBD6lfhxlQDVKgWoRE1id+OlrPef0CrddovBzZEy4ovw6Wu+v38Gwp4k7Jr4elx//DAE5KlxVgGznx/wEz65S8CmVuZHN0cmVhbQplbmRvYmoKMSAwIG9iago8PCAvVHlwZSAvUGFnZSAvUGFyZW50IDIgMCBSIC9SZXNvdXJjZXMgNCAwIFIgL0NvbnRlbnRzIDMgMCBSIC9NZWRpYUJveCBbMCAwIDYxMiA3OTJdCj4+CmVuZG9iago0IDAgb2JqCjw8IC9Qcm9jU2V0IFsgL1BERiAvVGV4dCBdIC9Db2xvclNwYWNlIDw8IC9DczEgNSAwIFIgPj4gL0ZvbnQgPDwgL1RUMiA3IDAgUgovVFQ0IDkgMCBSID4+ID4+CmVuZG9iagoxMCAwIG9iago8PCAvTiAzIC9BbHRlcm5hdGUgL0RldmljZVJHQiAvTGVuZ3RoIDI2MTIgL0ZpbHRlciAvRmxhdGVEZWNvZGUgPj4Kc3RyZWFtCngBnZZ3VFPZFofPvTe90BIiICX0GnoJINI7SBUEUYlJgFAChoQmdkQFRhQRKVZkVMABR4ciY0UUC4OCYtcJ8hBQxsFRREXl3YxrCe+tNfPemv3HWd/Z57fX2Wfvfde6AFD8ggTCdFgBgDShWBTu68FcEhPLxPcCGBABDlgBwOFmZgRH+EQC1Py9PZmZqEjGs/buLoBku9ssv1Amc9b/f5EiN0MkBgAKRdU2PH4mF+UClFOzxRky/wTK9JUpMoYxMhahCaKsIuPEr2z2p+Yru8mYlybkoRpZzhm8NJ6Mu1DemiXho4wEoVyYJeBno3wHZb1USZoA5fco09P4nEwAMBSZX8znJqFsiTJFFBnuifICAAiUxDm8cg6L+TlongB4pmfkigSJSWKmEdeYaeXoyGb68bNT+WIxK5TDTeGIeEzP9LQMjjAXgK9vlkUBJVltmWiR7a0c7e1Z1uZo+b/Z3x5+U/09yHr7VfEm7M+eQYyeWd9s7KwvvRYA9iRamx2zvpVVALRtBkDl4axP7yAA8gUAtN6c8x6GbF6SxOIMJwuL7OxscwGfay4r6Df7n4Jvyr+GOfeZy+77VjumFz+BI0kVM2VF5aanpktEzMwMDpfPZP33EP/jwDlpzcnDLJyfwBfxhehVUeiUCYSJaLuFPIFYkC5kCoR/1eF/GDYnBxl+nWsUaHVfAH2FOVC4SQfIbz0AQyMDJG4/egJ961sQMQrIvrxorZGvc48yev7n+h8LXIpu4UxBIlPm9gyPZHIloiwZo9+EbMECEpAHdKAKNIEuMAIsYA0cgDNwA94gAISASBADlgMuSAJpQASyQT7YAApBMdgBdoNqcADUgXrQBE6CNnAGXARXwA1wCwyAR0AKhsFLMAHegWkIgvAQFaJBqpAWpA+ZQtYQG1oIeUNBUDgUA8VDiZAQkkD50CaoGCqDqqFDUD30I3Qaughdg/qgB9AgNAb9AX2EEZgC02EN2AC2gNmwOxwIR8LL4ER4FZwHF8Db4Uq4Fj4Ot8IX4RvwACyFX8KTCEDICAPRRlgIG/FEQpBYJAERIWuRIqQCqUWakA6kG7mNSJFx5AMGh6FhmBgWxhnjh1mM4WJWYdZiSjDVmGOYVkwX5jZmEDOB+YKlYtWxplgnrD92CTYRm40txFZgj2BbsJexA9hh7DscDsfAGeIccH64GFwybjWuBLcP14y7gOvDDeEm8Xi8Kt4U74IPwXPwYnwhvgp/HH8e348fxr8nkAlaBGuCDyGWICRsJFQQGgjnCP2EEcI0UYGoT3QihhB5xFxiKbGO2EG8SRwmTpMUSYYkF1IkKZm0gVRJaiJdJj0mvSGTyTpkR3IYWUBeT64knyBfJQ+SP1CUKCYUT0ocRULZTjlKuUB5QHlDpVINqG7UWKqYup1aT71EfUp9L0eTM5fzl+PJrZOrkWuV65d7JU+U15d3l18unydfIX9K/qb8uAJRwUDBU4GjsFahRuG0wj2FSUWaopViiGKaYolig+I1xVElvJKBkrcST6lA6bDSJaUhGkLTpXnSuLRNtDraZdowHUc3pPvTk+nF9B/ovfQJZSVlW+Uo5RzlGuWzylIGwjBg+DNSGaWMk4y7jI/zNOa5z+PP2zavaV7/vCmV+SpuKnyVIpVmlQGVj6pMVW/VFNWdqm2qT9QwaiZqYWrZavvVLquNz6fPd57PnV80/+T8h+qwuol6uPpq9cPqPeqTGpoavhoZGlUalzTGNRmabprJmuWa5zTHtGhaC7UEWuVa57VeMJWZ7sxUZiWzizmhra7tpy3RPqTdqz2tY6izWGejTrPOE12SLls3Qbdct1N3Qk9LL1gvX69R76E+UZ+tn6S/R79bf8rA0CDaYItBm8GooYqhv2GeYaPhYyOqkavRKqNaozvGOGO2cYrxPuNbJrCJnUmSSY3JTVPY1N5UYLrPtM8Ma+ZoJjSrNbvHorDcWVmsRtagOcM8yHyjeZv5Kws9i1iLnRbdFl8s7SxTLessH1kpWQVYbbTqsPrD2sSaa11jfceGauNjs86m3ea1rakt33a/7X07ml2w3Ra7TrvP9g72Ivsm+zEHPYd4h70O99h0dii7hH3VEevo4bjO8YzjByd7J7HTSaffnVnOKc4NzqMLDBfwF9QtGHLRceG4HHKRLmQujF94cKHUVduV41rr+sxN143ndsRtxN3YPdn9uPsrD0sPkUeLx5Snk+cazwteiJevV5FXr7eS92Lvau+nPjo+iT6NPhO+dr6rfS/4Yf0C/Xb63fPX8Of61/tPBDgErAnoCqQERgRWBz4LMgkSBXUEw8EBwbuCHy/SXyRc1BYCQvxDdoU8CTUMXRX6cxguLDSsJux5uFV4fnh3BC1iRURDxLtIj8jSyEeLjRZLFndGyUfFRdVHTUV7RZdFS5dYLFmz5EaMWowgpj0WHxsVeyR2cqn30t1Lh+Ps4grj7i4zXJaz7NpyteWpy8+ukF/BWXEqHhsfHd8Q/4kTwqnlTK70X7l35QTXk7uH+5LnxivnjfFd+GX8kQSXhLKE0USXxF2JY0muSRVJ4wJPQbXgdbJf8oHkqZSQlKMpM6nRqc1phLT4tNNCJWGKsCtdMz0nvS/DNKMwQ7rKadXuVROiQNGRTChzWWa7mI7+TPVIjCSbJYNZC7Nqst5nR2WfylHMEeb05JrkbssdyfPJ+341ZjV3dWe+dv6G/ME17msOrYXWrlzbuU53XcG64fW+649tIG1I2fDLRsuNZRvfbore1FGgUbC+YGiz7+bGQrlCUeG9Lc5bDmzFbBVs7d1ms61q25ciXtH1YsviiuJPJdyS699ZfVf53cz2hO29pfal+3fgdgh33N3puvNYmWJZXtnQruBdreXM8qLyt7tX7L5WYVtxYA9pj2SPtDKosr1Kr2pH1afqpOqBGo+a5r3qe7ftndrH29e/321/0wGNA8UHPh4UHLx/yPdQa61BbcVh3OGsw8/rouq6v2d/X39E7Ujxkc9HhUelx8KPddU71Nc3qDeUNsKNksax43HHb/3g9UN7E6vpUDOjufgEOCE58eLH+B/vngw82XmKfarpJ/2f9rbQWopaodbc1om2pDZpe0x73+mA050dzh0tP5v/fPSM9pmas8pnS8+RzhWcmzmfd37yQsaF8YuJF4c6V3Q+urTk0p2usK7ey4GXr17xuXKp2737/FWXq2euOV07fZ19ve2G/Y3WHruell/sfmnpte9tvelws/2W462OvgV95/pd+y/e9rp95Y7/nRsDiwb67i6+e/9e3D3pfd790QepD14/zHo4/Wj9Y+zjoicKTyqeqj+t/dX412apvfTsoNdgz7OIZ4+GuEMv/5X5r0/DBc+pzytGtEbqR61Hz4z5jN16sfTF8MuMl9Pjhb8p/rb3ldGrn353+71nYsnE8GvR65k/St6ovjn61vZt52To5NN3ae+mp4req74/9oH9oftj9MeR6exP+E+Vn40/d3wJ/PJ4Jm1m5t/3hPP7CmVuZHN0cmVhbQplbmRvYmoKNSAwIG9iagpbIC9JQ0NCYXNlZCAxMCAwIFIgXQplbmRvYmoKMiAwIG9iago8PCAvVHlwZSAvUGFnZXMgL01lZGlhQm94IFswIDAgNjEyIDc5Ml0gL0NvdW50IDEgL0tpZHMgWyAxIDAgUiBdID4+CmVuZG9iagoxMSAwIG9iago8PCAvVHlwZSAvQ2F0YWxvZyAvUGFnZXMgMiAwIFIgPj4KZW5kb2JqCjcgMCBvYmoKPDwgL1R5cGUgL0ZvbnQgL1N1YnR5cGUgL1RydWVUeXBlIC9CYXNlRm9udCAvQUFBQUFDK0FwdG9zLUJvbGQgL0ZvbnREZXNjcmlwdG9yCjEyIDAgUiAvVG9Vbmljb2RlIDEzIDAgUiAvRmlyc3RDaGFyIDMzIC9MYXN0Q2hhciA1MCAvV2lkdGhzIFsgNjIwIDI5NCAzNDAKNjE5IDU1MiA1MTYgNTU2IDU4NiAyMDMgNzI5IDM2OSAzNTUgNzA3IDI2OCA2MDUgNTQ5IDU3MyA1NzkgXSA+PgplbmRvYmoKMTMgMCBvYmoKPDwgL0xlbmd0aCAzMzQgL0ZpbHRlciAvRmxhdGVEZWNvZGUgPj4Kc3RyZWFtCngBXZLLboMwEEX3/gov20WEgTwlhFSlisSiD5X2A8AeIkvFWMZZ8Pe946Sp1MVZHI9nGM+QHZvnxtkos/cw6ZaiHKwzgebpEjTJns7WibyQxup4s3Smx86LDMntMkcaGzdMsqqElNkHUuYYFvnwZKaeHvnsLRgK1p3lw9exTSftxftvGslFqURdS0MDyr10/rUbSWYpddUYxG1cVsj6u/G5eJLoCBn5tSU9GZp9pyl07kyiUqquTqdakDP/Qvn+mtEPt6tFXleMUuu8FlVRQAH0wFpCgVKFYV1DAaIF6wYKlNqm3C0UKLUrObqDAkQ3rHsogK5ZD1CAyoq1gwJU3rP2UIBS6UMaCqAp10ABLiclKEDl1PMABUptuHKJWTCIclcl3spAB1a8lYFSmtfvYHh0vOL7SvQlBGwj/QdpUbwA6+j+q/jJ88ATPzp0pwQKZW5kc3RyZWFtCmVuZG9iagoxMiAwIG9iago8PCAvVHlwZSAvRm9udERlc2NyaXB0b3IgL0ZvbnROYW1lIC9BQUFBQUMrQXB0b3MtQm9sZCAvRmxhZ3MgNCAvRm9udEJCb3ggWy01NDIgLTI3NSAxMzQyIDEwMTBdCi9JdGFsaWNBbmdsZSAwIC9Bc2NlbnQgOTM5IC9EZXNjZW50IC0yODIgL0NhcEhlaWdodCA2NTcgL1N0ZW1WIDAgL1hIZWlnaHQKNDc3IC9BdmdXaWR0aCA1ODcgL01heFdpZHRoIDE0MjAgL0ZvbnRGaWxlMiAxNCAwIFIgPj4KZW5kb2JqCjE0IDAgb2JqCjw8IC9MZW5ndGgxIDcxNTIgL0xlbmd0aCA0NjY3IC9GaWx0ZXIgL0ZsYXRlRGVjb2RlID4+CnN0cmVhbQp4AY1YCXAUV3p+fcyhmZGYETpAI9Q9tGYQjA6QkECyDI2Ebg4dI5gWQsxodIHFNdwYjAzGsO01poxNWCdrA3ay9rJl99hlr3AlrKkKyZbLJC5XHDtrbOz42NpU4qQ2u46DLU2+93okMOvdykwf7z/ef73//193747vGSROMkYEsjC2NbqDsN/Mr3Grje3dLZuwMIL7G0M7hreasFhEyIxjw6MHhkw4q5cQ246RweiACZNvca8aAcKEucW4F45s3b3fhGf+DPdVo9tjKXoWpRdtje5P6Sc3AMvbolsHTX7vW7gX7ogPpuhcmBB+hkn7E1cOtJlkEREZD0/cpAwojl814xjDUDrPP/bJumD2phm1vydOO0N/+NyeW3TwryPly7756cR1x1/bswhHrIRnZEiAt8cmfkGIs/ebn379OegpwvRtpprctDAp9S1KShvL4lJv2RlpQ1lS6ilNSlrpdSlcnJTWlySldSXXpe5gUgrNb5W65ielzgVJqWPBJal9viytLWqQ1hRdklYXJaVV85JSWyAptQaCUkvhsNRceF1qKkxKjf6k1OC/JK1UklL93KRU57surfAlJdV3SVouX5eWyUnpXvmMVCuXSfcUxKWagqRULSWlpdKYtGROXKqak5Qq51yXFudflyryk1J5/iVp0cK4VFp8r1RSHJcWzO+T/NBVmOed3avMVaW5Qt7sXl/evZJci4FUMCwVzJ+V0zsnNynl5yQlb+Xsmg2zqnJqNuSp7XScS8fZs+/JGemZWZ3Z7al2d2dqbi292tVtqea7RZwubUZVRrez2tFtq7Z2Z2gOzaoRLa3a3i2Aatd4zU0EVbVwl7nTJBRsG7clO9sMe/sGgztp+LvoVe3oMawnDdLdsyGc4LhT2vFHHyVz6tqM013hlwWCoZbg+fqOcEIUTml1JEiCQZzmnw1TcDDI3fEnGNMD3GxAZ2HAZuPGxtOACVMWE3+bDZhZxFJH/yQz+W7y18IHBLmb/HLqnHwq+R+WXJJpwuQQeZBsxX8fGcCfjg+SHWQv6SKDZA8ZJcPguA/XXWQLeY9ESQ+JkxA4hsn94H6YjGDGXlx3An6IRMh2SLqfrMb8MJMQBecoqHsh/TCTRPk7AW2G/GOQ2Q2ZA5ASJx1kPdkI/p1q64/O/dnZEw8ff+jY0QfHjjxw+ND9Bw/s37d3z+5d8Z07tm/bOnrfls0jw0ODA7H+aGRT38beDT1aeP267lBXR/vaNatXtbW2NDc1FkluR1oxl3A66pX6QUdJMUk4nBg6S4o5w1pv2BjSWBuUsahhX1tnuGGl1+fTvIrPUA3R30DP6IAemyJoEIFZmAsRbV1KW0dPWG7QI2wWMKHvQCZ9KZXIaKmRwdeHwkZjEHhGMeEmBoPRBJvvIrdMkRXZIO26PpAggh9iVG+CYwNL/SMaPNEUoz+o+JTwIEQl7MTlC0XqMXJNjTi5CRrkcTfpxxlbr4xzqVFP2JAjQ1ozuAnvN9jRNU4qlf3mOGLIMVk2rH6lvz2s+wwuonhTcGcYEeOiXt2n+GRNG09ezafcig+yeFKXULiTHQmVO9nVE77sRq89GQq/zHN8fQSlUgha+LJMiMqwqJxIHUVSFpkCpI3DyrzM2xm/97JKyBijigzB4Bi8YDiTCTiOxMZ5E+dmfIkAU6Sir8bGRZOiTkkQgbObuDGTuyjFbQfFTSmvEx6dmBE19kOUsJCqw6La1TTVxafzWAuKehmY18GbxpFXXFw6501AJjwAepwbS6Sp3stMkol6nRsDJ8WNQWCKjSeU7Q5B0Gg63o1byoPunvArLgL57AqOOvorKW5I8GuCyu207ghjARsS3JpgBKndBlDwN8hIa0PtClPeiBc579O0lSXFNLvksDLoVbREVpa+oyHhdte36fVIdOQaS7BE1BqIBPWwQVOOJprirkHaCv6WmNIYAYuCssHRAlRsnRwx+iNBDGV3ow6yHItSbpKT4AV/ghP93DKyDHGzugyHMlhnOJW6acpystykWCnFptQZXI4Z9QalQZ61WY8p/chAtT087B3SopBtqErUEJU6b0IkdaiuWRxcakiQNUH41oYcXBts34AipcGQdX2lnFDFQDQWpfBKH+peT5GUlStp0U7NaJB1Q43GIuBo0BhzSTFM0BuUqDyA5gF3EbkuhW4OPVRLqCesuwaUAQURVlU9Cre9ckzz6lqMRRzmwDRSUmy53Z1SzYmnPcAfG8JlXCb9EaXfRNDqvBs3fDdiCFx34pRWqg7GtlKrcddblYYBcNAzOmAIyDifPIAdi6YMaWd9448yQcQ0k4w1ZcJ19z00bygEOoMA4NCN4e+CI9NgI8hIBtFfauaKIQZo5oV9xhavMarRfDFZosZYv6zLbqVGoReWZ02gNkUMi7/JGItF4Qd6EnIPiFYg5HA/chkCGyP6VMZhmhiY1mRsw9rfIRItlQtBNe+nUTDG2uWIJkciwGJT8Hllw4K7PBSlyUXbbjv042hH78ctqndhLqEF5DVs2AGGooOKD80dOI3FlS0ftLciQ8IG8eq6ohscTPQ3ghniA4Y10EJvOHYEleggFpHqk6ODbG4jzGXRofZ5GxSfBhbeT+NOA4c+108vMR3ZaGxEtVn8Hj1Tl6t1dK2NaLhiILYugm1BdsuNMlvqKDKZBqGFQhoEmYxpqFg2HyKoNVuDiY02/20MkH5je9BktjOpsKwzbLRTpfSwsQODnUGDz10KIl0grhP9A10BC0WDZ/G3ILwqUs9LZ8sGj62MNQ1zfgud6k1hUtOAYW2X7prYV0wTnKa9plIrlW+42JHmN+x+LLQhwgaTbKPuTMlkYxhtzoFJMNd0AGOoovscPZgjkRQg+hF2yGNbI3WArrwaRdVHFe948o129MgIoIiiaVQ9DqQdncFE66ZgGi5Itn9vKFKaTOVOv+EEF3XBRJhXh9/AAadgM6WZgYMKoJi9VE8qepeTbxBAiByLGwsdnSD4T9CFQJGm6m7Qa4xowQFTmNW8tcjoqOjcsQ72tLEB1aD4bOhjiAAammx0BbGJMN9OsBkBpDhtITQruUaFNCKHUgOSQwyiNHP0QlBaSrPBA5weKS/zhLMrS+ktTVma4Dkbuj16sOJOd6HR67HIALY+bNSIMlnqraWPSogHFhoH1nYvbU2hsMUr0spCRRn7zCVFWSEulGGavg+dkEbLjKSd0vRpIg0km0yjjdJk171BO+T94Szd/v9ThlRgq2mkMUNoNwrYqWF/XJVgLlArVYDmyptutFJXLAg0alrXY1E8YW3MoBXqCniAz4RP1XCtOuUbYnMIfrdT7bABDjMwFKbuO5EELHmcILgRx6tmajtBdMPxq2hoKbsvJ5MEAUxxm6FDfCGP5XmKzAqDCqPz9gU1jBrpGQFXIz1TleRMVanrrq6fEm+uadp3icq0MLrRK9MSKZTgXHgYFr0WaAzIboSrhi1dAJ4A1msSnC2QYkBGuuFmja47FXNLUWj7v4wHUMIeLomG7vxdhHEYS6/r9vTvp9jv5k9nE2jxY5XTp+9USqocHPWGs54+v2ABjTTah0qxvoev0XRDVrDHiTu2Q4aipXjnJjmLxh6BxhREfDtrZpRxKm5DrKRNcXdjQ+HDUEIjdQ3BcBsc7paAj55eGjqWcwYqY3tQMx+5DtPcOMpK6mhQljfjOauew9MWNkqMZXQDcNsDrMnpeODZHMXWjD5E+442C89SnfTpGG8Ailvmakmt+VqkmBnXhT1A9IdrvdUa3ivGk7/Jp/0KoeGxyeMM6bLs9oCky5l40TCO01IUUzSF4bCLWwMpLurB8aCum3z0mdzF621dCAJ9Y3Ms9Tpg0/T717ngnyJjc6oPoV8Zm5T9PhoKY51yAA8L9Yohy71oiUA25Wu6ju1UV+g71bqweaUkrjifPhnQp5gUrzcf72i3QRemwqPx5Cv59HVpWtv9U9ri0EbV6lPqjNj3aqNZxm2gV3Yw7xJVRDH1i4GUUr1X78H7oc+YQxWn7ACYkU+7NrPkHLWECNfw3PAVEcTfkQuW53G+Sy7wPeSC+D7OLaRXHMBp4NxFenk/OSxeJKfEsxj/DneZRPn3SQ53nhD+MmkmBO9jeOfBz4UvW6W4+/AFgiMWXHliwxcKB0kjHrT3DHw3E/CN0ErsJB3c9LeJ/IBcJ99wMlfB9XMG9yW/kN/DP8X/UuCFecJB4Sf4j5vf3YRrllbMn4EvcSWkTM1bkCvnzbMUio6szQ7R7S6dUzhzJsfHiT2Ojyfl7r8r91TgEvRk5lYvXLTT4/P45wYqF1dVlOdkZ1ktPo+PC1QtqaqqXBxQ5lqzlSmKzWq1CdcmM8tVtbxi+fLJViH/28+4MmtF7ZKK6mXL6l59/tEfXupqKlUsltZbr310b+mi2tpFpffq4jMT/nXRBYGa4mBVXfWRR47sDPUvkqtLECZYTcT/xlcbG2LhVdMdot1qxefDuMiMhY3VZRUeWLmL83E+wSfM9AkC9xk3j/t88oPIZF7sr7i+lyx1t65wRZPv8x7eSyDxAmSeh8wZZDZRyBw1w56XNxtDiHWnxJZTuZlUrsfHvLblUN+tyryKctNxpRIjRCCgKBe4t341eZ/2wzP3f37+ixt1o8sfHr7xUse28nVLoPovL933pC//Zw+ceKn7N76uxp7V74U6quvnUN9gh6UedjhINnH/PBvqnVPqTcViZnYWL07rZKp+/z5XcfG5yev/fOPKY3/TN3jlxBVL3fnJf3rnXybf+fG/Ra+dfexqP80rKrsSsp1ktuoSHA5ihXj7lHjqHVOBtTX/F7jZfD83e/LXE09b6iZ+y2fcusLXTvytKYl7HZIE4noVMpiIoDkZk2hsU76IZ8Dlgi+5qjPd6STUIZObRTMVSzOMisdjhg/R493HPzh69IPj//Nh/4FDmz601PW98eSZNzZO+virI0Nb8HmbJ73J/xQ+F26SAlJEfKonzxG3K8oM4sqyxaV84kTalpcHoaXaUwHTGuYGaLoWLrmdoMjdAj7bo8yzWueVVy2ptFqzs3K4c12ntYuccnVD89qhr7dePbLxqZ3LvrYvey6r7UjgnedXe9QHoyd+sEhcvKmxLXT4cVVadax/YueRppbX1pQ/za1et6yWRro3+VvRzmxDfqbnpecRt90WzzWtCpZnVleXlU3bRGsoJ9eHrEHhZOXkIAhLfBk8v/LkR0cPffjYoV/u5SaTfGT9ruGS6CptmOc4Yc+bGSM3Xnzx462dzx5q054+vfFYQ1Q78mJPKi6igqhnEgl57M5wxNNJPM8J/TPd02EpD96OCdWfiyWfCoRnyhLuo20vDW59fffQ40EubdK5+Ck5dFCWdnT2jw57tn360gs3RkMruVu3rjzSHHqzbzk3p67/3Omnz5k2fCnmwP88dC/UkjeHzJhBJGrCVAiQbZnVyLfUulAbUEs2XwGfcp8zA8Kvffaj+Pb3fvyrCZ6f6OLLhrrWjXCcxbLr7yef4H4i7Orp3ZN54LPzf/7xgeS/u+Y7G/a3tLXGz7Xx24YGR6glh7EcL1g6Wadz/9whctY4cdCW9g/lZr4Kd7SxU1zaQy2rV7fgFN7+dqHY3rpkaUvL0iWtdE1PoUPkCx+RLOSyyy1YbXHIcjJhiGY5E1eRW8U8QTRpF5hrtXlOJS2Lzo89+dzk/xasqFy7c4Hw9uPLo6++OHGc1yrbi1srJ/awXP4vsUb4BN1HQtXPQqBSSxWE2DtCxAoFyWo2mbksY3P4liduHjx484mzNw8dunl2fWz+/Nj67mhRUdS99+NnLn66b9+nF5/5eO+bHSc7Q3pnpx7qPNmR8of/R+FD7CPZqjMt5Y8Zmzu9qciGG9SPSUvg3GjW7HtGw7Lw9gvhvpvZFSUT+6ikaPJL4RfCx2QhKVAzi13WGUUFMwvtxDfLFk+bWm+2bTTMLeUrK7JohqMM5wFYvAzrjSpUzG0D2Z8LKAvZn9PxFw+0frVr9apQ7NDIs72Ne86sbju9u/GrTWrD2vJtPZvOhpv2/SizoOWBvk51Uc2SqvzZTfuiq7asKCho2t/TVlNU6p2vZOU07u0LH2ybS63MQTqcFV/D+nnVDGtGhjNti81pjWemVrA8WOFBPkZpn/CgkVf6suG6B8ZWZPNlTzyrXrzIpb37bnBVX9OT+znjrS++eGsysrr1OiQ3c4f5nXwfcsyeAEjbaBemN/PzucOffEL3ZY7t4XRkxd5NVtBffXDFjt3bd5XUbR8dIP8HHrVQQwplbmRzdHJlYW0KZW5kb2JqCjkgMCBvYmoKPDwgL1R5cGUgL0ZvbnQgL1N1YnR5cGUgL1RydWVUeXBlIC9CYXNlRm9udCAvQUFBQUFFK0FwdG9zIC9Gb250RGVzY3JpcHRvcgoxNSAwIFIgL1RvVW5pY29kZSAxNiAwIFIgL0ZpcnN0Q2hhciAzMyAvTGFzdENoYXIgODcgL1dpZHRocyBbIDIwMyA1NjggNTI3CjQ1MiA2MDYgMjM5IDQ4NiA0ODcgNTI0IDUzMSA1MjUgMzIzIDU1MiAzMzQgNTg5IDU1MSAyNjAgNDM4IDU2MSA1NjEgMjYwIDc5MAozNDAgNjg2IDg1MyA0ODQgNTYxIDU1MSAyODYgMjg2IDU4NSA1NjYgNjA0IDU1OSA1MDAgNjkyIDQ1MiAyOTMgNzA3IDI5MyAzMDEKNDQyIDQ3OSA1NjEgNjgxIDUzNCAyODYgNTQwIDcwNiA3MjEgNTM0IDU1NiA3MDggNTc3IDg5MiBdID4+CmVuZG9iagoxNiAwIG9iago8PCAvTGVuZ3RoIDU2NiAvRmlsdGVyIC9GbGF0ZURlY29kZSA+PgpzdHJlYW0KeAFdlN1um0AQhe95ir1MLyKvWTCJhJCiRJF8kbaq2wfgZ7GQakAYX/jt+51xmqq5+CwfZmd2zizL5nn/sh+H1W2+L1N7iKvrh7Fb4nm6LG10TTwOY7JNXTe067uyZ+2pnpMNyYfreY2n/dhPriwT5zY/SDmvy9XdPXVTE7/o2beli8swHt3dr+eDPTlc5vl3PMVxdT6pKtfFnnJv9fy1PkW3sdT7fUd8WK/3ZP1b8fM6R0dHZGxvLbVTF89z3calHo8xKb2vytfXKolj9ymU+1tG078vTbdVKbxPfZWUaYoE77NGMiDB+10umSHB++JRMkeC93kquUMCiy1aIIHFQdEHJBC1yo9IYKOdojUSiG4lGyQgLbdFAqUyRTskEO0lIxKIWhs9EqisUoFZCBZHSbwKZCuJV0FuLYlXQVQbBbwKpCoHvAoqy2DAq0B2kngVTNIkXoP5zawUXoP53VkUr+Hmt1AuXgVt6BQCXgX7PkjiVXhPChKvgo3MAl6D+c01yQyvgkPR6JiBQZOywI/BRjrQDK+CqErRqYG0XLxm5rewynjlsLSvusrwKlhsEq/8UVTDYUIGFiwXr5n5LWwxXnnBWJxrOGxu0JWOjHEaRK1JvGbml4MjilfBRjrQHK+ib7yiOX4FXVkUv7ycyII5cx/+vvj5p3vAsErBjDUn2jIooxbow0DquBi0QYM6rpwpCOT/m+j+6Tvxca/by7Jwpe1jYrddt3gY48f3Zp5mdWn8Acg3KNgKZW5kc3RyZWFtCmVuZG9iagoxNSAwIG9iago8PCAvVHlwZSAvRm9udERlc2NyaXB0b3IgL0ZvbnROYW1lIC9BQUFBQUUrQXB0b3MgL0ZsYWdzIDQgL0ZvbnRCQm94IFstNTAwIC0yNzUgMTE4MiAxMDEwXQovSXRhbGljQW5nbGUgMCAvQXNjZW50IDkzOSAvRGVzY2VudCAtMjgyIC9DYXBIZWlnaHQgNjU3IC9TdGVtViAwIC9YSGVpZ2h0CjQ3NiAvQXZnV2lkdGggNTYxIC9NYXhXaWR0aCAxMjY5IC9Gb250RmlsZTIgMTcgMCBSID4+CmVuZG9iagoxNyAwIG9iago8PCAvTGVuZ3RoMSAxMDkyOCAvTGVuZ3RoIDc0NjAgL0ZpbHRlciAvRmxhdGVEZWNvZGUgPj4Kc3RyZWFtCngBjVoJXFN3nv//38tFwpEEASVgEh/BIyAKcnk1goCABwJqAiKJAREFlah4YvGEplZ7WHW0rVVbtXWmfdFWsZ+O7RztjFN1pp1jd+bT2V4zdTud2s7uTHfWwst+/+8laJ3Z/Wx4x//83df764bAxlZiIL2EJ5P8nb51RP6N2I/XPn/3BpvS51fi/eaKdW2dSl81jpCE3W0dW1Yo/aR+QpJ0K1t9LUqfDOJdsBIDSp9OwTtjZeeGzUo/8bt4f9ix1h+ZTxqBfqDTtzmCn7yPvm2Nr7NVWT/hUdZfF2iNzFM3IVyCMvd/PCnmishCoiGZ4I8jRpKDIcrNTdiNHsUfwHAH/2ts3C+aE6b/jRh0MrDfP7fxDmt8vDI3f5AO3YjZqGP0abBH+WGfdvfQG4ToMwfp3/8D85GJ4VeRK9w8KWxdNjlsbcoJWJfmPGFtzAlbGyaGrZ6JN6zurLB1SXbYujj7hnWRM2ytH19lrRsfttZOCFsXTjhvrRlvsy4YV2adP+68dd64sHXu2LC1OjNsrcp0Wisz2qxzMm5YKzLC1nJH2FrmOG+dLYStpWPC1hL7Desse9jqsp+3PmC7YZ1pC1tn2J6wTrflWKeNDlinjg5bi61ha5G111qYHrAWpIet+ek3rFPSbljz0sLW3LTz1smTAtaJWTOs2VkB64Txy6wO4MpItYxaKoxxWcfwqaOW2lNnWG3T0bCObrOOHj8yeWl6Stialhy2WvJHTW0cWZA8tTHVVcPaKaydNGpa8sqGxGLzIlOxcZHZY/TEFccuUhdzi1S4Yz0JBfGLDMX6RdpizaJ4j96j8RBPTLFuEY9ZnYfzGAnvcqnpFfooqXdWD2jDtdWirqZRpP2io449XQsbRE2/SBY1NLpDlB7w7H3kEZJeUi0+Wue+wBM0PSGOK13oDqn4A54S4iROJ27lT25G+k4nveePoM0urJYbbBca8m685PZwR+mzJcr43WUYGUnUJeyPmMO/Dt/i/0xMhIRvR2/pWPgLdQoxK32ynewknfjbRFrwx9pbyTrSTepIK9lIOkgbVqzGcz1ZRf6F+EgDCZB6rGgj27B6H1mJHd14dqG/h3jJWkDaRuZhv1uG4MPKDsx2A3qPDImtr0WvHfB3A+YiwGwBlAB8ZwlpwvouV9V3jh453Ldv757du3b2PrijZ/u2rVs2b+reuGF9oGvd2jWdHatXta9sW9Ha4l/u8zYva1ra2OBxL1m8qL5uYc2C+fPmVldVzqkoH2c16mOyaMigLxVKW/XZWSSkN6BpyM6ioqZU1MqD4gKnDUp126tr3WWzLXa7xyLYRZeocpSx29cS9EcnPACBXdgLENV1QvXCBretLOiVd2Gk/ls9Zb6IQZTnIi2RK613i+VOjMszSr9C7mOh0p1z33RldFqwiaQmGGwJEd4BMC5LiMoNdenDHnDiEcTlTsEuuFsBKqQjsfZ6bylasdEWtVUAg23ASJbj9i8RBmik1eAWbd4VnjlYTTiHKF91AyRf2Ky0vaLNb7OJGoewvMYdtIvUK1gi/Vo3JEZ9lqBdsNs8noHwD9LYasEOWBwpCQm0f2HIRfvrGtxXjIit/fXuCxzlSr1wlQzMua/YCHHJo/AcbwkbZEtsrEOqKTRzgdPJ6y1XXIT0yrMqeUDu+8GFPKYswhgl/gFOGTPK60KZMiIX4qp/QKXMuKIQVBjTKWO9yupxkdU6zBjZzGuEQySWJz3yD1KCIl16tUvninHFcnEcdMGGLmDkNayNoeRiLI2jlhBgggMMD9DeUIzLckWGpAy9Rnuxko31AmBkGUfYsnsAAaPC+CK8IhwsanBfjCWALz+xooT9srPKQtx8p3DXrBe6ocCyEJ3v9MK0q9HlHWU2mLXoqnOztV4LbN7u8czOzmLWZXMLrRbBExoxIriuLGQ0llYHS2HosDXZwEI+TabXGXSLzOSYoQnGqTBb3lHpF8q9WCLAbXBVYsi/2OYVl3udaNqM5UFM2/w+tpokhzjeEaIqB51JZkJumlhRL7SWiAahZHjmAfKAMqNhM1qhRKTJitTLhDLbyPagX1gOC3TVuNssKzw+wBZdgk9UCSWWkIqUwLtGUrBUFiLzneCtGja4wFnTCCdlwrAFg7NtIZcq0+f3sf5sO/w+GJkSZs9mThvdUWYLii6f34sVZR55cXYWSAiWCT5bC4IH2IXk6gSWHBoYlvoGdzC2RWgRIGGXK+gD2xab32MJevyyxEEOSCPZWeq70SkSnDgWAxz+FXgM2Mhyr7BcGWDeef9Y2/0DK7Dq3jGhiqEDsVWMaryDVUJZC1aw29ci8rA4u60FGYuZDKmR48b/uggghhfZoFMZeNA4jdkN62Fe7qGDKyi2fbu7crhbjmkYg8oxUbEVUZXJLM9tF1dZxA4PsxdliU/sXW4L2ozCVIE9ZDurwGyFV1Q7KsRevw98ICbB9jBQhQGbezlsGQDLvcGoxWGbKnMYk7gGur8HJEIqrQdqzsGkIPbW2Lwem9eLUSQFu8UmqvG2rfAx42Jhtwb4cdUg9uPlC9ZhL2EOZBG1yAArfK2CHcEdYx5ZrrL6gL0KFuIWiSUYFIIiBYmOciwG+ExRk1nJXrjWOQVfK5TI8Nl8rfLecpArS4fRZykT7B4s4RxM7kxwiHPL2cMfhDWKTfA2tcMUNAdtxUFErSYEXFWmf7EXacFmtJXbZFX7YMlMCJWs5wEgZWEMPFbeDxCMmk5nqEnruDuCQYe41qks1slQQVmtW6xhSNmllS80upwil1KESaYgWov4gagARTHhqR2VEK8Lpmdhu20ih1QmBw1lfyXbaomMRLZhRA67LGsirygkGBR6FaQaBl+Mla8Yh6hzQNGiCjQo01rGThSm3AbRyh6QBHIVBtAGKpbn2CUz4o10VA6IHfDk1MgYYJp3+eD1PsEyEH6zBjHSi55X8HgYelwwO7ZDBh1UADNxAbLun4oigklBbnCIBqxiLCgDylPvEHGBKdDM5hTBAQWGZHoZnoj0roTfJOhBcrLcZNGxDbyjjykCThrxu1aLuNLjbFGAaZRXpQ0RFZHbv1CuNhrhDYJdizgGCSCg2cQ6J5KIzFufvCMTJs5CCLNKWi6QcthQpEGSiUiEOZQ9CFxLmCNy6A63hAv4RtIJRewVIxSFOKpFtEcMFoxxsQj0Qb+3BakPiRpSJkWW6axUgjygaFzQbTcLTfVutUXFPAseJW5SVAq3glzYguH5TYiETFqKJHVsLjg8yQQpb2bShmvKz26nDvD+cVdQ9/9DBlOQtSnGyISwaJSpY4T976h4RUFVDAGCK6ewUcVYUUPQ8Olg0O9DhdUUzzw0NtOEcTN4KgZrxRHeIJvt4LuGYQcNYFju1rsZ+wYYgWw8BkwYIccfKKZtwKQRjP8AAS1C95VwmECAkdWK6CBfwJPtPDItOwYDxvZtcnrQKme3F6vK2R3xJEPES2Pvi/oR8IpOY749KQwDY4leGIbIeiEai2JYZVEDY6bNCHFNlVWXCU7QD04NUW1mZAEs0gg2pwaDBkFJKQIL/1dQgBK5uCQeROdvD4g9UH0wqIv75zO6+9fHyRuY80PLccNvBiXiDvpS0VDK6hcoUIxhcWgi9NvzFjM3WIVcTtyTDuUh5or3JsmRTPYQNLZA4mvlYMYWRuW2QnZpBdz9o/XuHiBhknoLwjCKFG91pp3dFiY62eZEeMZap0cpuXqYbeySXWqX02ZrR51VSlFtIVGibUM0wGpdphzkgih42n1IzYhDLO54RqKWqmXVMb4ABKONTifTlc8iQbG4OuQAlcM93VLswXfFQPizNBavIBoOSR53fdBmM5owFbSZ8aEh7mWuqIrMCfIYsrgmM7KKcbDXGQwq61hNHssFq+sgBPbFpi+y6EHT8PfXUef/NY3kVFqPeCU2C5vtTBTiYmELioVSQbTZliIkYrAizRMMIp0GBfZNtditPNkUzUpjlQGrYiJrLWn4RrvbjcVWcDQQvpjGPpeGsW2LYgsAG0MbjKIT/f8UG7My2sie8iVzFyoggoJflRlBGlwabMD3oV1MZ4gjdKAbn8aitkzJUUYJ4d9C3XCZ6FS/JqI6SDrUPURUrcedi/559M8RkUtCfz8R+TARNbUYP4P+M7h/i7uPzOV/Rczq9eSE6mWi0wqEU7nIKlUPOanKw3s77kKyimsnNv5DUqZqJyfpZ2Q//0dyEnAPa36JdRhTrYrswXrue+Qk/wlZwR0mNtVmcoR/hhD1j4mBD5IY1uZ3ktmqWsyVkzdxN9FnCeEqyXO4e+X3FeLn3GQP7ipC8I2I7zD8YnHaxs4K7aSQTCZ6MopkkQSSjnO80ZhJIilkLBlDHFhtJ1aSTUYimcVgVz7SkY1YiEDSyBSSRxJx5seRcTjh5Ml4UkB0gJeKcx8TycB5Sw7JJRNJHJlAJhE10ZJ4ws752K+Z9JMbNJZOpcvoDvoT+jkd4jK4qVw7t597nQvzdfxa/ih/mb+lyld1qy6q/qouUreq/67J1FRpujQHNb/T6rQl2j3an2j/rHtA16E7rntNdysmPWZ+zNqYbTEnYn6Lv7/q0/Tj9MX6Zv0eYFQxtPxb6ipQmgC6s0mOK3VCii11rDpDpR/RrlcZjRPTMxITKRcgugAOmnKNb+ea8vBwmswpxZMmd5nsJseYzPwpBXm5yUkjNGq7yU4zCwoLCvKnZApjNElCdEar0Wj5t6RRGZMmZWTk5kqz+JmDP6StqmnTphbULq5vXndq567jNaWFY1TqqjuXPsjJyMhh91OqHw5+Xbs6O6uiYNoCd01P//bVNS1TnNX5UCkkS1Qv44RLC21ZXHF6lU6jwVFrQCUTCxqLc/JMoHI9zaMCb+cT7byO/v0q/ctrvUPv7btMf/YHdcmdq3SL1McZuQchChQnRLUJEBOgfYGku+J1qamj0ARQYwRoLoNqZlBNdplnbTLjXCM47LkK2/b8vFzGf6aAnCK+85+blu8/0/G7M9JvacaiRxefe0J6/5tdD83ctPgbdclz51adGZUS2rX1e0sPOzu9GwKPb2qd3ZgNG+sI31ZnqOthWSkuQ1waMen4wCgSAyXkOnPNxcBfNiaDy59izoDkk1OEiRzErUkakZwM5IV58Rx3+13p4yeeoKPfDf7tdPyrsWtPN526tnTptVPPXTdeMh77KyJowfXrtEj0vnW4dbfr0NdHDn/92KmTJ95dCclCDup4yEEPuzdeTgL7hij7CuMqc9IITiU4gGyY1bd+SSc89bT0m/ekLz8Lfdq1/tZLn6lLTkjv/erX0nvPHOn6LCTeCoAzJmMDYBvIKFesWqcjKoCPiYJn0pVRJMGU5FvkG4c8XNfQQe6suuSwVHdIch5mXgs4/NeAE8MkFIUjg3HKOroXisiXD63h6oe+yyDUPjH0ZETCMyBhB7Mdq80WT8yQcWpUxqbiYhMouSvl0dx9Ui4otOfbmRi4r96TPoKore+tvHrMb3hF33x63anry5qvn37kVQ8nbeKKd0vfmF+ihTdu0qKX8lefWjNv54Invj565G+Ptr7a/WT7y9Jfj0Q4UjGOZMnwej3RQDK6+yWTB5/LMwl4iq9wH164MGRTlwy9w+XfucqEFIFDWwCHJ7GvAoIiEyaOPGxhJh/RQhBrmOfEx/AaXk3U38Im+zfbAuehAmXIxt8cepdb9vuhy0C4hesb2jtUzF0cmhfRxW8BTU3iLwEKH6FZwWlPwt6N6pJvPMcj1KlPYm0CsbqMfEwcHxuruY9Tc3EOiy7ADsyMV+UtvkU/qKS/eTM0UyrslibNVJcM3uJH3bmq+u7gN7z6m/qoDP8G6DHMunSMK44LaIdlKHsOg8tECKYGuI/PDwylg7h3VTmANPmbn7PIwmx0AaDEsrgP/zMYCHMCRZJ3rQueJ7u+3YRYIIc8HIB+2vPTDRt+2iPdpBlbjxzdIr2vLmm+sm/3haVDX3Dneh7s3xWB/x3AT4Z/I8rEpKQkJREbMCQMU3pvlGFYtLC/RIGHnyvYouiGNr4ROBicu3zWSPfAvBGFS+dJP6a5VZsr9j4oXVOXVD2zo/cVm2HuzmbpZZpft3HG0NvcL4pWVXftgNbmhm+rpsMDcsholzkrTm0aNzopQ0fso3j4YzTUMEWUjcnMzM9TYovs7mMnIvQUsKCfnCQUyJEesymjOSYObt6j//7Qq03Hli56pL7kOzuP/ri542cP7/rXna/QF3t2Hpx5pO+pHy3d9aHZ/frh1Vtz89oWljeU2sc1H+hc/3Rt/bmewMY2/7QFLmGC9/DWXecXM53iXyn4H0JaWpLoitHqAhqO46EMuHmec9Jkn4m5od1EH5N28qK0S3X+yJFvFrF9J8DfL7EPGflygpoL6KNMRTiCDYxg4TKfNUD3wPdvr7l0+XsvXbq05gvz3s8P8/MHf/rexYvv8UWDFw5/vhcQWcZBFGL1gEvPEzVzmahRsJzgY86C689S2hv0Ufr4VSkFprVdtUf2OQ7/hmfH7lhm+RrewMO3ZRD6Ya3nKXk1CofZPaX7pe7v00l01jVaQnNfkTa9Lr0qvQa4T6v87IbZBr45AKtaFb7Nv8B/gHplHLG7TKn6gE4QEkjsCG3AmkYMTGJIHnJgg9xkpU4pyCi8m6qhUKjQJIzVaMYii+SrWEKhT9U/XPcczbq2vbk1eKrt1Y3VD3W6ntKWhqpani2Qvr7VZHb1LN3dP5mb3dO0Ys3mQ7PTqva2D208VN3Yu2zO2/yy1ZVLQNtJ6CIRvJtRO6W7jKN0Bm1AQwJqfSCRj5KG+iJXpmusFi5vitgXNANiFCK1puRkbmvH0UkxT53Ne37tppeaWweO7+l/cHv7YxPG9pvrKhHShr6a5+368OyZjwIPvfHyK2+uq5EeqvJBd6vCX/LXZOkg3selxqUSo04bSFGQyzk1J2dYKrJppwjI4Shi7kmq2Xuur+96p6/r1Q7+ec321Qf2z9yxbPU+/nm+84pp7Qfnzn3UVfVkYFnHj8SNp5esXd399HwWTZheEAWivMfrA3EkkGoA9kRjlHdo5q5OGPYUFqEiijBF6aC3ZZZ7Vh7LOftMzJTn5q0+kDV+b+vevgfNgU/Onvm3rsb5XOydqwcqPA+1VtBNtauvvvzq1QgF18F7KmpXxBtLMklA+GUERNlH3jUXy/kOrq64Ngs69tFcpJ6gdpkIruDEO8ubf3T4Jx9z3FAVndbbvm4H2G95RfJxI/j+LVsfNu/948EnP+n96qOE8THNJ7zt/rYnF3Ke/kcPQgc2iGMuJJHEsg43YgRv0gTi9PhHP71cXUL/LOeuNwn5eflTZnJ5eUlM/kl4mX50+vSoB7oaWhs8OZ98wlf0FVV1L3Tu9jYW9A1egT+WSX3826oFqKfTULdPJ3NIDSl2pc/Pn9deVVlamp/hmDEjOz05OSsmO5vkaxBoE+RaCnzfZFhNqOmQ8PFwwgZnsYA3paCwUClrFftDPSdXWIly8CtMiZRbhcpa2WJY+Bs2VuY7YwsKCpPGaOhfn/l+/WNHbNu+uvn55y8+nPPgxkOzq3bENXdOXNBQlz/T4Vlg33x28ZIXtvacqa071+vt6fY19+yk9bOdD68p3yj1zdlcvmiPpfDBvXte2OKtmDBjjKm2YHojLdZPqxwzeUnalISc9BHWxN1NR9xNRxsajjY1HGkMrOno6lzXuaaTXn1g2Wz+kXQWEU8ikr4L+Y9AVos18hptgBKUdkz6sD/mfSzjy46HMGBiNewYjdZ08kz2uV3PHTybPr+y81A2XOzrae2vf3doP9dUvuYB/7Qh2crx/zdok7pC/pYwXtarqCai1psRsPw9Hwonz9bnFBfn5Eydyt8czFXtLZwwoZDdERq/AI2sMklglQlRaxiZuiiZ91cmJ8/SgbekOfTDX0hOlAQ/oO9IRUN36B0JHwOElYp/AbRYVCZqghSg8IpQzdQGZpEB8pLolU07Jp7J8WRXP+JXaQdpo7efxSz8B4zp/PuQloMILvPoVLtdkZkm4EBFIENCCoLcYECy3eal/IPs7FEpwhSYNZlOPqtxntl+6sA5SLPtgFM1L33+nJUHJo6aGsIgf/PwtParL0K0SysU0coN37StrjVsOKpDmaphHWr+QYf/SAfQZp/b/ezjZ0fPY0qUEX3//D2IlEj1lYrwH7HaDDlzJAJEJEAxp4gkjHsNXS4Goh8e3KSD11evvn7w8Z+vXfvzxzt6i4p6O9q3FRRsM2756PiJT7Zu/eTE8Y+27G0+u6rjRZ/vxY5VZ5sZzpPSMVUiYlMkMySa4g2BUbJpwoDiWVyAgGXbrDNF5KtUXWMyx5rovZnh5Cn1lOc7N7OksH3lUzl0xN6+HVtXPzF+XL90TD3lxPzlSAvPf7S+bo5kor9/I3TxamCu1D+3mcVH6Rj/Ps4fIjSY4wMITKkJsQiQVBVNnHKEnmXCp95dj08pRIGMVIkIPVbOFHw+SNjyclPr5e0dR3M0J6XJnQezxu9Zsffh3dIx+t/VDYE/nH3+3wJNc4/cuU5/31ZFNyzooG+8dInV5LA3rp//HWJYkssAy4d3Rn0o6ptMr3JQZF75tGb84xtHpFSuqbXxN8/MXfGdzNKsIbkKXoGM0wOZTpIru1hNwrjRiayyG6lFZSfzg4SnVHYIZqjsWBU0JVMu6xB2WRUgKB/w0bIunqN3ap9Y98DJR1Y1b1u7P/DU/EL/vvnz+tqmn9ruaViX293Seah6Wvsj5oz5DzYEmirr55TbLRWddbP8JfaMuZvrVy52zR5b4ByZOqfLPXdtxRgWjVg2aFR9D/6FbKCJjzfErNIaNAFzxEdznYjKUUdlGSFPTgSKw37avSPn9OkzX32V41kFp+Vi+z74oG9osNHXxyAfCf+F/xf+ZiTO6QMJKoDVD+daJdMq3s9YL4zkWvqbFw6fG12/YM2h7HMn1TnnE15/nts+dLxk5dTG6dyFwdzDU1cz6OzU5BlAV6pA9uEUVVOu6d4qsFsKhqiNCi9KjyLK/YafMJiL3QZ8Ww9gt1wFGlh807EqUDMcm1g2kpWDKjAxkV04veBpiXTtpVufXfnij89J18QvbwPibd48+CVvGszlRw3eghXHgK6dgKyF/9pciTEavZrGx3E6FT64WcZTQh9olD+uaCEAa6mdjgWaFBpDV1T8/aJ0wSXd4pKkT0ukSxf/q5Su5kyFdJ+UnC8tpC9PoZ9LWycPfSbLAB7DZGCSvx81BoNWE9DoEaeZx7JcIkuijh2FFBYqVbE2nhPaa4sXpGVK20I0mya/KD0+ccy8dUukY8EZFW4w9AmfPpjbvWRVDsMwG9zMAAb5+15DCQ8d4qRHBq+cgKzPp6z0p/ak2SA5ibsw9ClX2Mv9pG/T0KQ+/FMF7It/W12hykTdg9KbpOOUkUF+E3Z3TT0aGmAnBxqNPjY2QPUqGbJJ/ur3meI5bf5MDt7NpVr8/fV1Bzutx1VzHGUFsc/EV3mz7nwMOE2A/wf1BJz9oaJEQtAZ1QGK46JYBsmEQgLFBTJqPlXOhRAfcBw2HD4h+qQm+vPNHZ3b92852/zGgV2XmhfsWyi9wJ3eQ892Xli+Yvdja7Zeamk6F1hx7lCldP0Qo/258Nf0efIfsCL9RQ0xM0xyZB4+gqOZRVVVRYVz5ugr8wsrKgrzK7GrV/qTvMtEzJcJpQaVWt6plFt1rEhJuSc5a16cMNUdY1DglHZJf1qWuswlg5u/sPlhLyQrU8Hf1GSSXMhSKz/fBx4/Pcst5qahBtCF0GVHOXXQkJ/+Jz17SKZ/j3Sci8eJI6zxoo6060gOnHFWJseOssyFeRp8QZpT6N6F62dMX1/7UHdgZ5t0fD/MdOTpZ6mDJu/7mVR4+1eS+wKTRZV0nP46AktD2jUyrLoCc/4UbmxespkdUXHaqk2BXW39tRtmzFhfJx1/h1778lf0zIWg9N/Sv59+Vvqd9CcEDMAy42Y/DayCzGK/MuesdRvWrifkfwC0lkA4CmVuZHN0cmVhbQplbmRvYmoKMTggMCBvYmoKPDwgL1RpdGxlIChzYW1wbGUtcGRmKSAvUHJvZHVjZXIgKG1hY09TIFZlcnNpb24gMTMuNi4xIFwoQnVpbGQgMjJHMzEzXCkgUXVhcnR6IFBERkNvbnRleHQpCi9BdXRob3IgKEFuZHJlYSBFbGxhIFJlbW9yZXJhcykgL0NyZWF0b3IgKFdvcmQpIC9DcmVhdGlvbkRhdGUgKEQ6MjAyNDExMDUwMzUxNTdaMDAnMDAnKQovTW9kRGF0ZSAoRDoyMDI0MTEwNTAzNTE1N1owMCcwMCcpID4+CmVuZG9iagp4cmVmCjAgMTkKMDAwMDAwMDAwMCA2NTUzNSBmIAowMDAwMDAzMjU1IDAwMDAwIG4gCjAwMDAwMDYyMTYgMDAwMDAgbiAKMDAwMDAwMDAyMiAwMDAwMCBuIAowMDAwMDAzMzU5IDAwMDAwIG4gCjAwMDAwMDYxODAgMDAwMDAgbiAKMDAwMDAwMDAwMCAwMDAwMCBuIAowMDAwMDA2MzQ5IDAwMDAwIG4gCjAwMDAwMDAwMDAgMDAwMDAgbiAKMDAwMDAxMTk4MyAwMDAwMCBuIAowMDAwMDAzNDY3IDAwMDAwIG4gCjAwMDAwMDYyOTkgMDAwMDAgbiAKMDAwMDAwNjk4OSAwMDAwMCBuIAowMDAwMDA2NTgyIDAwMDAwIG4gCjAwMDAwMDcyMjggMDAwMDAgbiAKMDAwMDAxMjk5OCAwMDAwMCBuIAowMDAwMDEyMzU5IDAwMDAwIG4gCjAwMDAwMTMyMzIgMDAwMDAgbiAKMDAwMDAyMDc4MSAwMDAwMCBuIAp0cmFpbGVyCjw8IC9TaXplIDE5IC9Sb290IDExIDAgUiAvSW5mbyAxOCAwIFIgL0lEIFsgPDUyYjBhYjRmNDRhZGFlOGIzNGY3MDUxNDViODZjY2UyPgo8NTJiMGFiNGY0NGFkYWU4YjM0ZjcwNTE0NWI4NmNjZTI+IF0gPj4Kc3RhcnR4cmVmCjIxMDE0CiUlRU9GCg=="
                      }
                    }
                  }
                }
              }
            }
          },
          "4xx": {
            "description": "Client side errors",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/APIErrorResponse"
                }
              }
            }
          },
          "5xx": {
            "description": "Server side errors",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/APIErrorResponse"
                }
              }
            }
          }
        }
      }
    },
    "/inference/model-info": {
      "get": {
        "tags": ["inference"],
        "summary": "Get Model Info",
        "description": "Get model info",
        "responses": {
          "200": {
            "description": "Success",
            "content": {
              "application/json": {
                "schema": {
                  "allOf": [
                    {
                      "$ref": "#/components/schemas/APIResponse"
                    },
                    {
                      "type": "object",
                      "properties": {
                        "data": {
                          "type": "array",
                          "items": {
                            "$ref": "#/components/schemas/GetModelInfoResponse"
                          }
                        }
                      }
                    }
                  ]
                }
              }
            }
          },
          "4xx": {
            "description": "Client side errors",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/APIErrorResponse"
                }
              }
            }
          },
          "5xx": {
            "description": "Server side errors",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/APIErrorResponse"
                }
              }
            }
          }
        }
      }
    },
    "/inference/model-facts": {
      "get": {
        "tags": ["inference"],
        "summary": "Get Model Facts",
        "description": "Get model facts",
        "responses": {
          "200": {
            "description": "Success",
            "content": {
              "application/json": {
                "schema": {
                  "allOf": [
                    {
                      "$ref": "#/components/schemas/APIResponse"
                    },
                    {
                      "type": "object",
                      "properties": {
                        "data": {
                          "type": "array",
                          "items": {
                            "$ref": "#/components/schemas/GetModelFactsResponse"
                          }
                        }
                      }
                    }
                  ]
                },
                "example": {
                  "success": true,
                  "message": "Model facts retrieved successfully",
                  "data": {
                    "en": {
                      "Changelogs": {
                        "1.0.0": "2023-03-01: Initial release"
                      },
                      "Mechanism": {
                        "Input_data_source": "Left coronary angiogram videos",
                        "Input_data_type": "Video data",
                        "Model_type": "X3D architecture",
                        "Outcome": "Prediction of LVEF from left coronary angiograms",
                        "Output": "Continuous LVEF percentage value",
                        "Target_population": "Adult patients aged ≥18 years who received a coronary angiogram and transthoracic echocardiogram (TTE)",
                        "Time_of_prediction": "N/A",
                        "Training_data_location_and_time-period": "University of California, San Francisco (UCSF), Dec 12, 2012, to Dec 31, 2019"
                      },
                      "Other_information": {
                        "Clinical_impact_evaluation": "N/A",
                        "Clinical_trial": "LVEF Prediction During ACS Using AI Algorithm Applied on Coronary Angiogram Videos (CathEF) - NCT05317286",
                        "Clinical_trial_URL": "https://www.clinicaltrials.gov/ct2/show/NCT05317286",
                        "Contact_info": "robert.avram.md@gmail.com",
                        "Github": "N/A",
                        "Outcome_definition": "LVEF",
                        "Related_model": "CathAI",
                        "Scientific_publication": "N/A"
                      },
                      "Other_results": {
                        "GradCAM": "GradCAM consistently highlighted epicardial LCA vessel segments and septal perforators predominantly during systole as the strongest predictors of low-LVEF."
                      },
                      "Summary": {
                        "Approval_date": "2023-04-17",
                        "Description": "CathEF is a video-based deep neural network (DNN) designed to predict left ventricular ejection fraction (LVEF) from left coronary angiograms.",
                        "Developed_by": "Dr. Avram, Dr. Tison and Dr. Olgin",
                        "Development_period": "2020-01-01 to 2023-04-17",
                        "Last_update": "2023-04-17",
                        "License_date": "2023-03-01",
                        "Licensed_to": "Montreal Heart Institute",
                        "Name": "CathEF",
                        "Version": "1.0"
                      },
                      "Uses_and_directions": {
                        "Appropriate_decision_and_support": "N/A",
                        "Before_using_this_model": "Make sure you have at least three views available to input into the model (RAO Caudal, AP Cranial and LAO Cranial are the best)",
                        "Benefits": "Estimation of LVEF from standard LCA angiogram videos without additional",
                        "General_use": "CathEF is an automated estimation of LVEF from standard coronary angiogram videos. It can be used to provide real-time, dynamic assessment of cardiac function during coronary angiography without additional equipment or procedures. It is especially useful for patients with acute coronary syndrome or those at increased risk of contrast-induced nephropathy.",
                        "Safety_and_efficacy_evaluation": "N/A",
                        "Target_population_and_use_case": "Adult patients aged ≥18 years who received a coronary angiogram of the left coronmary angiography."
                      },
                      "Validation_and_performance": [
                        {
                          "UCSF_test_dataset": {
                            "AUC_ROC_LVEF_40": 0.911,
                            "AUC_ROC_LVEF_50": 0.879,
                            "ICC_continuous_LVEF": 0.77,
                            "MAE_continuous_LVEF": 8.5,
                            "Pearson_correlation_continuous_LVEF": 0.71,
                            "Sensitivity_LVEF_40": 83.9,
                            "Specificity_LVEF_40": 81.3
                          },
                          "UOHI_external_validation": {
                            "AUC_ROC_LVEF_40": 0.906,
                            "AUC_ROC_LVEF_50": "N/A",
                            "ICC_continuous_LVEF": 0.62,
                            "MAE_continuous_LVEF": 7,
                            "Pearson_correlation_continuous_LVEF": 0.72,
                            "Sensitivity_LVEF_40": 77.9,
                            "Specificity_LVEF_40": 88.6
                          }
                        },
                        {
                          "UCSF_study_cohort": {
                            "Female_percentage": 35,
                            "LVEF_over_40_percentage": 82.2,
                            "LVEF_under_40_percentage": 17.7,
                            "Mean_age": "64.3±13.3",
                            "Number_of_angiograms": 3960,
                            "Number_of_patients": 3404
                          },
                          "UOHI_external_validation_cohort": {
                            "Female_percentage": 33,
                            "LVEF_over_40_percentage": 76.3,
                            "LVEF_under_40_percentage": 16.8,
                            "Mean_age": "68.6±13.3",
                            "Number_of_angiograms": 776,
                            "Number_of_patients": 744
                          }
                        }
                      ],
                      "Warnings_and_limitations": {
                        "Clinical_rationale": "CathEF has not been validated for use with right coronary angiograms.",
                        "Discontinue_use_if": "N/A",
                        "Generalizability": "The model's generalizability to other healthcare institutions and populations requires further validation.",
                        "Inappropriate_decision_support": "CathEF performance may be affected by administration of contrast during angiography, which can temporarily depress LVEF.",
                        "Inappropriate_settings": "The model has not been tested on patients with atrial fibrillation, congenital heart disease, or prior cardiac surgery.",
                        "Risks": "CathEF's performance may be less accurate at extreme LVEF values."
                      }
                    }
                  }
                }
              }
            }
          },
          "4xx": {
            "description": "Client side errors",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/APIErrorResponse"
                }
              }
            }
          },
          "5xx": {
            "description": "Server side errors",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/APIErrorResponse"
                }
              }
            }
          }
        }
      }
    }
  },
  "components": {
    "schemas": {
      "PredictRequest": {
        "required": ["inferences", "age", "gender", "outputMode"],
        "type": "object",
        "properties": {
          "inferences": {
            "type": "array",
            "description": "DICOM converted frames",
            "items": {
              "type": "array",
              "items": {
                "type": "array",
                "items": {
                  "type": "array",
                  "items": {
                    "type": "integer"
                  }
                }
              }
            }
          },
          "age": {
            "type": "integer",
            "description": "Age of the patient"
          },
          "gender": {
            "type": "string",
            "enum": ["MALE", "FEMALE"],
            "description": "Gender of the patient"
          },
          "outputMode": {
            "type": "string",
            "enum": ["OHIF_ANNOTATIONS", "HTML", "WEB_APP", "PDF"],
            "description": "Output mode"
          }
        }
      },
      "APIResponse": {
        "type": "object",
        "properties": {
          "success": {
            "type": "boolean",
            "example": true
          },
          "message": {
            "type": "string",
            "example": "Operation successful"
          },
          "data": {
            "type": "object",
            "example": {}
          }
        }
      },
      "APIErrorResponse": {
        "type": "object",
        "properties": {
          "success": {
            "type": "boolean",
            "example": false
          },
          "message": {
            "type": "string",
            "example": "Bad Request"
          },
          "errorCode": {
            "type": "string",
            "example": "BAD_REQUEST"
          },
          "data": {
            "type": "object",
            "example": {}
          }
        }
      },
      "GetModelInfoResponse": {
        "type": "object",
        "properties": {
          "modelName": {
            "type": "string",
            "description": "Model name",
            "example": "cathef"
          },
          "version": {
            "type": "string",
            "description": "Model version",
            "example": "0.8.0"
          },
          "dicomTargetLevel": {
            "type": "string",
            "enum": ["PATIENT", "STUDY", "SERIES", "INSTANCE"],
            "description": "DICOM target level",
            "example": "SERIES"
          },
          "dicomUploadMin": {
            "type": "integer",
            "description": "Minimum number of DICOM frames to upload for inference",
            "example": 1
          },
          "dicomUploadMax": {
            "type": "integer",
            "description": "Maximum number of DICOM frames to upload for inference",
            "example": 5
          },
          "supportedDicomModalities": {
            "type": "array",
            "description": "Supported DICOM modalities",
            "items": {
              "type": "string",
              "example": "XA"
            }
          },
          "supportedOutputModes": {
            "type": "array",
            "description": "Supported output modes",
            "items": {
              "type": "string",
              "enum": ["JSON", "OHIF_ANNOTATIONS", "HTML", "WEB_APP", "PDF"],
              "example": "JSON"
            }
          }
        }
      },
      "GetModelFactsResponse": {
        "type": "object",
        "properties": {
          "en": {
            "type": "object",
            "description": "Model facts in English. See example for more details."
          }
        }
      },
      "PredictResponse": {
        "type": "object",
        "properties": {
          "htmlBase64": {
            "type": "string",
            "description": "Base64 encoded HTML"
          }
        }
      }
    }
  }
}
